import type { Metadata } from "next";
import Providers from "@/context/Providers";

export const metadata: Metadata = {
  title: "Prueba desarrollador frontend",
  description: "Generated by Danilo Amaris",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
